spring.application.name=payment-service

server.port=8086

eureka.client.service-url.defaultZone=http://localhost:8080/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

razorpay.key-id=rzp_test_TbUv6bTD5qxWIC
razorpay.key-secret=7Ij17oVQRe5RqYVE5UdB0A11