spring.application.name=driver-service

server.port=8084

eureka.client.service-url.defaultZone=http://localhost:8080/eureka/

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


# H2 Database
spring.datasource.url=jdbc:h2:mem:driver_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#kafka property
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=driver-service-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
