spring.application.name=ride-service


server.port=8085

eureka.client.service-url.defaultZone=http://localhost:8080/eureka/

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


# H2 Database
spring.datasource.url=jdbc:h2:mem:ride_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


#kafka property
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


#location API
locationiq.api-key=pk.b318972a0fa57ba23878296c769e5a94
locationiq.base-url=https://us1.locationiq.com/v1